"use client";
import {useState} from "react";
import "./dorori.css";
const TYPES=[["Roy","방전형"],["obby","생각과다형"],["popo","미룸형"],["mumu","눈치형"],["nugu","벽쌓기형"],["Nabi","길잃음형"],["pingo","도파민형"],["bamba","꾹참형"],["moa","나몰라형"]];
const MOODS=["지침","불안","미룸","외로움","갈등","무기력","성취","관계","밤","기대"];
const LINES=[["오늘은 애쓴 만큼 쉬어도 되는 날이야.","에너지가 낮다는 건 게으름이 아니라 신호야.","조금 느려도 괜찮아. 나는 네 편이야."],["아직 오지 않은 일을 전부 해결하지 않아도 돼.","지금 손에 잡히는 한 가지만 같이 보자.","불안한 마음도 네가 소중한 것을 지키려는 방식이야."],["시작은 3분이면 충분해. 완벽은 나중에 와도 돼.","가장 쉬운 조각만 꺼내볼까?","다시 고르는 순간이 더 중요해."],["말하지 못한 마음이 있다면 나에게 먼저 맡겨도 돼.","작은 인사부터면 충분해.","네 마음은 여기까지 잘 왔어."],["네 마음에도 자리가 있다는 걸 잊지 말자.","바로 답하지 않아도 돼.","무엇이 불편했는지 한 문장으로 정리해볼까?"],["오늘의 목표를 아주 작게 줄여도 괜찮아.","침대 밖으로 나온 것만으로도 한 걸음이야.","따뜻한 물 한 모금부터 해보자."],["그거 정말 잘했어. 네가 만든 변화야.","기뻐해도 돼. 다음을 서두르지 않아도 돼.","오늘의 너에게 조용히 박수 보낼게."],["오늘 한 번은 네 취향을 먼저 말해볼까?","모두를 편하게 하려는 마음은 다정해.","네가 편안한 관계도 충분히 가능해."],["오늘의 남은 일은 내일의 너에게 넘겨도 돼.","이 밤에는 해결보다 회복이 먼저야.","오늘의 마음을 여기 두고 쉬어도 돼."],["처음이라도 괜찮아. 한 걸음씩이면 돼.","기대하는 너를 나도 응원할게.","잘하고 싶은 마음을 너무 무겁게 들지 말자."]];
const OPEN=["충전이 필요한","생각을 잠시 내려놓고 싶은","시작의 문턱을 낮추고 싶은","내 마음을 먼저 살피는","가까워질 용기를 모으는","방향을 다시 찾는","재미와 리듬을 찾는","참아온 마음을 풀어내는","작은 현실부터 마주하는"];
function mood(v:string){if(/지쳤|피곤|힘들/.test(v))return 0;if(/불안|걱정|무서/.test(v))return 1;if(/미루|해야|시작/.test(v))return 2;if(/외로|혼자/.test(v))return 3;if(/싸웠|화나|갈등/.test(v))return 4;if(/무기력|싫/.test(v))return 5;if(/잘했|성공|기뻐/.test(v))return 6;if(/친구|눈치|사람/.test(v))return 7;if(/밤|잠/.test(v))return 8;return 9}
export function DororiClient({user,signIn,signOut}:{user:{name:string}|null;signIn:string;signOut:string}){const [view,setView]=useState("start"),[type,setType]=useState(0),[input,setInput]=useState(""),[msgs,setMsgs]=useState([{me:false,t:"왔구나. 오늘은 어떤 하루였어? 한 문장이어도 괜찮아."}]);const [turn,setTurn]=useState(0);const send=(v=input)=>{if(!v.trim())return;const m=mood(v),tail=(v.length+turn)%2?"지금의 너를 충분히 이해해.":"오늘은 이 한마디만 기억해도 좋아.";const text=`${OPEN[type]} ${TYPES[type][0]}가 들었어. ${LINES[m][(v.length+turn+type)%3]} ${tail}`;setMsgs(x=>[...x,{me:true,t:v},{me:false,t:text}]);setInput("");setTurn(turn+1)};if(view==="account")return <main className="d"><button className="back" onClick={()=>setView("start")}>‹</button><div className="sprout">🌱</div><h1>나의 기록을<br/>안전하게 이어가기</h1><p>ChatGPT 계정으로 시작하면 캐릭터와 성장 기록을 연결할 수 있어요.</p><a className="primary" href={signIn}>ChatGPT로 로그인 · 회원가입</a><button className="link" onClick={()=>setView("home")}>로그인 없이 둘러보기</button></main>;if(view==="chat")return <main className="d chat"><header><button className="back" onClick={()=>setView("home")}>‹</button><b>🌱 {TYPES[type][0]}<small>오늘 곁에 있는 친구 · 540가지 반응</small></b></header><div className="talk">{msgs.map((x,i)=><div key={i} className={x.me?"me":"bot"}>{x.t}</div>)}</div><div className="chips">{["에너지가 바닥났어","마음이 복잡해","작은 일부터 할래"].map(x=><button key={x} onClick={()=>send(x)}>{x}</button>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="오늘의 마음을 들려줘"/><button>↑</button></form></main>;if(view==="home")return <main className="d"><header><small>오늘의 돌봄</small><button onClick={()=>setView("account")}>☻</button></header><h1>안녕{user?`, ${user.name.split("@")[0]}님`:"!"} ☀️</h1><p>오늘도 잘 하고 있어요.</p><div className="hero"><div>🌱</div><small>Lv. 07 · {TYPES[type][1]} {TYPES[type][0]}</small><h2>작은 돌봄을<br/>선물해볼까요?</h2><b>●●●○○ 230 / 500 잎사귀</b></div><h2>오늘의 성장 퀘스트</h2>{["💧 물 한 잔으로 하루 시작하기","👟 10분 산책하기","💗 나에게 따뜻한 말 한마디 하기"].map(x=><button className="mission" key={x}>{x}<i>+</i></button>)}<button className="primary bottom" onClick={()=>setView("chat")}>친구와 대화하기</button>{user&&<a className="logout" href={signOut}>로그아웃</a>}</main>;return <main className="d start"><div className="brand">dorori</div><p>나를 키우는 작은 습관</p><div className="sprout">🌱<span>오늘도<br/>수고했어!</span></div><h1>{TYPES[type][1]} {TYPES[type][0]}와<br/>작은 습관을 시작해요</h1><button className="primary" onClick={()=>setView("home")}>시작하기</button><button className="link" onClick={()=>setView(user?"home":"account")}>{user?"오늘의 돌봄으로":"로그인 · 회원가입"}</button></main>}
