// @ts-nocheck
"use client";
import {useEffect,useRef,useState} from "react";
import "./dorori.css";

const URL="https://bltdjctrqlrimpcpdfbl.supabase.co",KEY="sb_publishable_UX5qAOrr5Kk5Hj2li0IQfA_Z2j2lPZF";
const TYPES=["Roy","obby","popo","mumu","nugu","Nabi","pingo","bamba","moa"],LABELS=["방전형","생각과다형","미룸형","눈치형","벽쌓기형","길잃음형","도파민형","꾹참형","나몰라형"],IMAGES=["roy","obby","popo","mumu","nugu","nabi","pingo","bami","moa"];
const TEST=["혼자 쉬는 시간이 없으면 금방 에너지가 바닥나요.","생각이 꼬리를 물어 결정을 미룰 때가 많아요.","해야 할 일을 알지만 시작을 자주 미뤄요.","다른 사람의 표정과 반응을 지나치게 살펴요.","상처받을까 봐 먼저 마음의 벽을 세워요.","무엇을 원하는지 몰라 방향을 잃은 기분이 들어요.","새로운 자극이나 재미를 계속 찾게 돼요.","힘들어도 괜찮은 척 참고 넘기는 편이에요.","복잡해지면 일단 모른 척 피하고 싶어져요."];
const QUEST_XP=[10,10,15,15,15,15,20];
const LEVEL_QUESTS=[
 ["물 한 잔 천천히 마시기","창문을 열고 세 번 깊게 숨쉬기","5분 동안 몸을 가볍게 움직이기","오늘 내 기분 한 단어로 적기","작은 공간 한 곳 정리하기","나에게 따뜻한 말 한마디 하기","오늘 해낸 작은 일 하나 기록하기"],
 ["10분 동안 휴대폰 없이 쉬기","좋아하는 노래 한 곡 집중해서 듣기","오늘 고마웠던 일 한 가지 적기","미뤄둔 일의 첫 단계만 시작하기","내 몸이 보내는 신호 하나 알아차리기","잠들기 전 내일 할 일 하나만 정하기","나를 웃게 하는 작은 행동 해보기"],
 ["걱정되는 생각을 종이에 모두 적기","할 수 있는 일과 없는 일을 나누기","불편한 감정에 정확한 이름 붙이기","믿을 만한 사람에게 안부 보내기","부담스러운 일 하나를 10분만 해보기","오늘 거절해도 되는 일 하나 찾기","실수한 나에게 친구처럼 말해주기"],
 ["가까운 사람에게 솔직한 기분 한 문장 전하기","도움이 필요한 일 하나 부탁해보기","비교하게 만드는 환경에서 잠시 벗어나기","내가 중요하게 여기는 가치 세 가지 적기","미뤄둔 대화의 핵심을 메모해보기","나를 지치게 하는 관계의 패턴 살펴보기","작은 약속 하나를 끝까지 지켜보기"],
 ["상대에게 원하는 것을 구체적으로 말하기","싫은 부탁에 정중하게 거절해보기","두려워 피했던 일에 15분 도전하기","최근 상처받은 순간과 이유 적기","내 책임과 상대의 책임 구분하기","나만의 회복 루틴 하나 만들기","한 주 동안 지키고 싶은 경계 정하기"],
 ["중요한 선택의 장단점을 직접 결정해보기","불편했던 관계에서 내 입장 표현하기","완벽하지 않은 결과를 세상에 내보이기","오래된 후회에서 배운 점 세 가지 적기","내 욕구를 먼저 챙기는 시간 만들기","두려움 속에서도 해낸 경험 떠올리기","앞으로 줄이고 싶은 습관 하나 실천하기"],
 ["나를 제한하는 믿음 하나 반박해보기","진심으로 원하는 목표를 한 문장으로 선언하기","갈등 상황에서 피하지 않고 대화하기","실패 가능성이 있는 작은 도전 선택하기","남의 기대와 내 기대를 구분해 적기","내 강점을 사용해 누군가 돕기","한 달 뒤의 나에게 응원 편지 쓰기"],
 ["중요한 관계에 묵혀둔 진심 전하기","오랫동안 미룬 결정을 내려보기","두려운 상황을 위한 행동 계획 세우기","내가 반복하는 방어 행동 인정하기","용서가 필요한 나의 모습을 마주하기","삶에서 포기할 것과 지킬 것을 정하기","가치에 맞는 행동을 하루 동안 선택하기"],
 ["삶의 방향을 바꿀 한 가지 행동 시작하기","관계에서 필요한 경계를 분명히 세우기","실패를 감수하고 원하는 일에 지원하기","숨겨온 감정을 안전한 사람에게 털어놓기","과거의 나에게 감사와 작별 편지 쓰기","내 삶의 우선순위 다섯 가지 다시 정하기","혼자 결정하고 결과까지 책임져보기"],
 ["가장 두려운 목표를 30일 계획으로 나누기","진짜 원하는 삶을 위한 어려운 선택하기","도움받는 용기와 돕는 책임을 함께 실천하기","상처 준 사람과의 관계 방식을 스스로 결정하기","내가 바꿀 수 없는 것을 받아들이는 글 쓰기","지금까지 성장한 증거 열 가지 기록하기","다음 100일의 나에게 성장 약속 세우기"]
];
const QUEST_ICONS=["💧","🌿","✍️","🧭","💬","🛡️","⭐"];
function Character({type,className="character"}:{type:number,className?:string}){return <img className={className} src={`/characters/${IMAGES[type]}.png`} alt={`${LABELS[type]} ${TYPES[type]}`}/>}
const NAV=[{label:"홈",view:"home",icon:0},{label:"퀘스트",view:"quests",icon:1},{label:"기록",view:"record",icon:2},{label:"친구",view:"friends",icon:3},{label:"설정",view:"settings",icon:4}];
function SpriteIcon({index}:{index:number}){return <i className="sprite-icon" style={{backgroundPosition:`${(index%5)*25}% ${index<5?0:100}%`}}/>}
function BottomNav({view,setView}:{view:string,setView:(v:string)=>void}){return <nav className="bottom-nav">{NAV.map(n=><button key={n.view} className={view===n.view?"active":""} onClick={()=>setView(n.view)}><SpriteIcon index={n.icon}/><span>{n.label}</span></button>)}</nav>}
type Message={me:boolean;t:string;emotion?:string};

export function DororiClient(){
 const [view,setView]=useState("start"),[mode,setMode]=useState("signup"),[status,setStatus]=useState("");
 const [form,setForm]=useState({name:"",nickname:"",age:"",gender:"",email:"",password:""});
 const [profile,setProfile]=useState({name:"도리",nickname:"도리"}),[type,setType]=useState(6),[testStep,setTestStep]=useState(0),[scores,setScores]=useState<number[]>(Array(9).fill(0));
 const [xp,setXp]=useState(230),[done,setDone]=useState<number[]>([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[notice,setNotice]=useState(""),[notifications,setNotifications]=useState(true);
 const [messages,setMessages]=useState<Message[]>([{me:false,t:"왔구나. 오늘은 어떤 하루였어? 한 문장이어도 괜찮아.",emotion:"listening"}]);
 const talkRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(view!=="chat")return;requestAnimationFrame(()=>talkRef.current?.scrollTo({top:talkRef.current.scrollHeight,behavior:"smooth"}))},[messages,loading,view]);
 useEffect(()=>{const saved=localStorage.getItem("dorori_progress");if(saved){try{const d=JSON.parse(saved);setXp(d.xp??230);setDone(Array.isArray(d.done)?d.done.filter((x:any)=>typeof x==="string"):[]);if(Number.isInteger(d.type))setType(d.type);if(d.profile)setProfile(d.profile)}catch{}}},[]);
 const today=new Date().toISOString().slice(0,10);
 const save=(next={})=>localStorage.setItem("dorori_progress",JSON.stringify({xp,done,type,profile,questDate:today,...next}));
 const sync=async(next={})=>{const token=localStorage.getItem("dorori_token");if(!token)return;const data={xp,done,type,name:profile.name,nickname:profile.nickname,quest_date:today,test_done:localStorage.getItem("dorori_test_done")==="yes",...next};try{await fetch(URL+"/auth/v1/user",{method:"PUT",headers:{apikey:KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({data})})}catch{}};
 const field=(key:string,value:string)=>setForm(x=>({...x,[key]:value}));
 const auth=async()=>{
  if(mode==="signup"&&(!form.name||!form.nickname||!form.age||!form.gender))return setStatus("모든 정보를 입력해 주세요.");
  if(!form.email||form.password.length<6)return setStatus("이메일과 6자 이상의 비밀번호를 확인해 주세요.");
  setStatus("계정을 확인하고 있어요…");
  const body=mode==="signup"?{email:form.email,password:form.password,data:{name:form.name,nickname:form.nickname,age:form.age,gender:form.gender,xp:230,done:[],type:6,quest_date:today,test_done:false},options:{emailRedirectTo:location.origin}}:{email:form.email,password:form.password};
  const r=await fetch(URL+(mode==="signup"?"/auth/v1/signup":"/auth/v1/token?grant_type=password"),{method:"POST",headers:{apikey:KEY,"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();
  if(!r.ok)return setStatus(d.error_description||d.msg||"입력한 정보를 다시 확인해 주세요.");
  if(mode==="signup")localStorage.setItem(`dorori_profile_${form.email}`,JSON.stringify({name:form.name,nickname:form.nickname}));
  if(mode==="signup"&&!d.access_token){setStatus("가입 완료! 인증 메일의 링크를 누른 뒤 로그인해 주세요.");setMode("signin");return}
  const meta=d.user?.user_metadata||{};let cached={};try{cached=JSON.parse(localStorage.getItem(`dorori_profile_${form.email}`)||"{}") }catch{}
  const nextProfile={name:meta.name||cached.name||form.name||"도리",nickname:meta.nickname||cached.nickname||form.nickname||form.email.split("@")[0]},nextXp=Number(meta.xp??230),nextType=Number.isInteger(meta.type)?meta.type:6,nextDone=Array.isArray(meta.done)?meta.done.filter((x:any)=>typeof x==="string"):[];
  localStorage.setItem("dorori_token",d.access_token||"");localStorage.setItem(`dorori_profile_${form.email}`,JSON.stringify(nextProfile));setProfile(nextProfile);setXp(nextXp);setType(nextType);setDone(nextDone);save({profile:nextProfile,xp:nextXp,type:nextType,done:nextDone});setStatus("");const tested=meta.test_done===true||localStorage.getItem("dorori_test_done")==="yes";if(tested)localStorage.setItem("dorori_test_done","yes");setView(tested?"home":"test");
 };
 const answer=(score:number)=>{const next=[...scores];next[testStep]=score;setScores(next);if(testStep<8){setTestStep(testStep+1);return}const winner=next.indexOf(Math.max(...next));setType(winner);localStorage.setItem("dorori_test_done","yes");save({type:winner});sync({type:winner,test_done:true});setView("result")};
 const finishQuest=(i:number)=>{const currentLevel=Math.min(10,Math.floor(xp/100)+1),key=`${currentLevel}-${i}`;if(done.includes(key))return;const nextDone=[...done,key],nextXp=Math.min(1000,xp+QUEST_XP[i]),newLevel=Math.min(10,Math.floor(nextXp/100)+1);setDone(nextDone);setXp(nextXp);save({done:nextDone,xp:nextXp});sync({done:nextDone,xp:nextXp});setNotice(newLevel>currentLevel?`LEVEL UP! Lv. ${newLevel} 달성 🎉`:`+${QUEST_XP[i]} XP 획득!`);setTimeout(()=>setNotice(""),2600)};
 const send=async(text=input)=>{const trimmed=text.trim();if(!trimmed||loading)return;const next=[...messages,{me:true,t:trimmed}];setMessages(next);setInput("");setLoading(true);try{const history=next.slice(-20).map(x=>({role:x.me?"user":"model",text:x.t}));const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({character:IMAGES[type],message:trimmed,history:history.slice(0,-1)})});const d=await r.json();setMessages(x=>[...x,{me:false,t:d.reply||"잠깐 멈칫했어. 다시 말해줄래?",emotion:d.emotion||"neutral"}])}catch{setMessages(x=>[...x,{me:false,t:"앗, 잠깐 생각이 꼬였어. 한 번만 다시 말해줄래?",emotion:"neutral"}])}finally{setLoading(false)}};
 const level=Math.min(10,Math.floor(xp/100)+1),levelXp=level===10?100:xp%100,currentQuests=LEVEL_QUESTS[level-1],levelDone=currentQuests.filter((_,i)=>done.includes(`${level}-${i}`)).length;

 if(view==="account")return <main className="d account"><button className="back" onClick={()=>setView("start")}>‹</button><Character type={6} className="character account-character"/><div className="account-title"><h1>{mode==="signup"?"나만의 도로리 만들기":"다시 만나서 반가워요"}</h1><p>{mode==="signup"?"간단한 정보로 성장 여정을 시작해요.":"이메일과 비밀번호로 로그인해요."}</p></div>{mode==="signup"&&<><div className="form-grid"><input placeholder="이름" value={form.name} onChange={e=>field("name",e.target.value)}/><input placeholder="닉네임" value={form.nickname} onChange={e=>field("nickname",e.target.value)}/></div><div className="form-grid"><input placeholder="나이" inputMode="numeric" value={form.age} onChange={e=>field("age",e.target.value)}/><select value={form.gender} onChange={e=>field("gender",e.target.value)}><option value="">성별 선택</option><option>여성</option><option>남성</option><option>기타/응답 안 함</option></select></div></>}<input placeholder="이메일" type="email" value={form.email} onChange={e=>field("email",e.target.value)}/><input placeholder="비밀번호 6자 이상" type="password" value={form.password} onChange={e=>field("password",e.target.value)}/><button className="primary" onClick={auth}>{mode==="signup"?"회원가입 완료하기":"로그인"}</button>{status&&<p className="status">{status}</p>}<button className="link" onClick={()=>{setMode(mode==="signup"?"signin":"signup");setStatus("")}}>{mode==="signup"?"이미 계정이 있어요 · 로그인":"처음이에요 · 회원가입"}</button></main>;
 if(view==="test")return <main className="d test"><div className="test-top"><span>나의 도로리 찾기</span><b>{testStep+1} / 9</b></div><div className="test-progress"><i style={{width:`${(testStep+1)/9*100}%`}}/></div><Character type={6} className="test-character"/><p className="eyebrow">간단 성향 테스트</p><h1>{TEST[testStep]}</h1><p>지금의 나와 얼마나 가까운가요?</p><div className="answer-grid">{[[1,"전혀 아니에요"],[2,"조금 아니에요"],[3,"반반이에요"],[4,"조금 그래요"],[5,"매우 그래요"]].map(([n,t])=><button key={n} onClick={()=>answer(n as number)}><b>{n}</b><span>{t}</span></button>)}</div></main>;
 if(view==="result")return <main className="d result"><span className="result-badge">테스트 완료 · +50 XP</span><Character type={type} className="result-character"/><p>{profile.nickname}님의 성장 파트너</p><h1>{LABELS[type]} {TYPES[type]}</h1><p>지금의 마음을 가장 잘 이해하는 친구예요.<br/>매일 작은 퀘스트로 함께 성장해요.</p><button className="primary" onClick={()=>{const next=xp+50;setXp(next);save({xp:next});sync({xp:next});setView("home")}}>파트너와 시작하기</button></main>;
 if(view==="chat")return <main className="d chat"><header><button className="back" onClick={()=>setView("home")}>‹</button><b><Character type={type} className="avatar"/> {TYPES[type]}</b></header><div className="talk" ref={talkRef}>{messages.map((x,i)=><div key={i} className={x.me?"me":"bot"}>{x.t}</div>)}{loading&&<div className="bot thinking">생각 중…</div>}</div><div className="chips">{["에너지가 바닥났어","마음이 복잡해","작은 일부터 할래"].map(x=><button key={x} onClick={()=>send(x)} disabled={loading}>{x}</button>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} disabled={loading} placeholder="오늘의 마음을 들려줘"/><button disabled={loading}>↑</button></form></main>;
 if(view==="home")return <main className="d app-screen home-new">{notice&&<div className="level-notice">{notice}</div>}<header className="app-header"><div><h1>안녕, {profile.nickname}님! ☀️<br/><b>오늘도 잘 하고 있어요!</b></h1></div><button className="bell-button" aria-label="알림"><SpriteIcon index={9}/></button></header><section className="character-card"><div className="level-copy"><strong>Lv.{String(level).padStart(2,"0")}</strong><span>{LABELS[type]} {TYPES[type]}</span></div><Character type={type} className="home-character"/><div className="speech">오늘도<br/>수고했어!</div></section><div className="full-xp"><i style={{width:`${levelXp}%`}}/><b>EXP {levelXp} / 100</b></div><section className="stat-grid">{[[5,"집중력",Math.min(99,35+level*4)],[6,"실행력",Math.min(99,31+done.length*2)],[7,"관계력",Math.min(99,28+level*3)],[8,"자기이해",Math.min(99,40+level*5)]].map(([icon,label,value])=><div key={label as string}><SpriteIcon index={icon as number}/><span>{label}</span><b>{value}</b></div>)}</section><section className="quest-preview"><div><h2>오늘의 성장 퀘스트</h2><button onClick={()=>setView("quests")}>전체 보기</button></div><button onClick={()=>finishQuest(currentQuests.findIndex((_,i)=>!done.includes(`${level}-${i}`)))} disabled={levelDone===7}><span className="preview-icon">{levelDone===7?"✓":QUEST_ICONS[currentQuests.findIndex((_,i)=>!done.includes(`${level}-${i}`))]}</span><b>{levelDone===7?"Lv. "+level+" 퀘스트를 모두 완료했어요!":currentQuests[currentQuests.findIndex((_,i)=>!done.includes(`${level}-${i}`))]}</b><em>{levelDone===7?"완료":"+"+QUEST_XP[currentQuests.findIndex((_,i)=>!done.includes(`${level}-${i}`))]+" EXP"}</em></button></section><BottomNav view={view} setView={setView}/></main>;
 if(view==="quests")return <main className="d app-screen"><header className="tab-header"><div><small>LEVEL {level}</small><h1>성장 퀘스트</h1></div><span>{levelDone}/7 완료</span></header><p>레벨이 오를수록 더 깊은 고민과 용기가 필요한 도전이 열려요.</p><div className="quest-list">{currentQuests.map((text,i)=>{const key=`${level}-${i}`,completed=done.includes(key);return <button className={`mission ${completed?"completed":""}`} key={text} onClick={()=>finishQuest(i)}><span className="quest-icon">{completed?"✓":QUEST_ICONS[i]}</span><span><b>{text}</b><small>+{QUEST_XP[i]} XP</small></span><i>{completed?"완료":"+"}</i></button>})}</div><BottomNav view={view} setView={setView}/></main>;
 if(view==="record")return <main className="d app-screen"><header className="tab-header"><div><small>나의 성장</small><h1>기록</h1></div><span>Lv. {level}</span></header><section className="record-hero"><b>{xp} XP</b><p>지금까지 모은 경험치</p><div className="full-xp"><i style={{width:`${levelXp}%`}}/></div></section><div className="record-grid"><div><b>{done.length}</b><span>완료 퀘스트</span></div><div><b>{level}</b><span>현재 레벨</span></div><div><b>{Math.min(10,level+1)}</b><span>다음 목표</span></div></div><section className="growth-note"><h2>오늘의 성장 한 줄</h2><p>작은 실천이 쌓여 {profile.nickname}님만의 단단한 변화가 되고 있어요.</p></section><BottomNav view={view} setView={setView}/></main>;
 if(view==="friends")return <main className="d app-screen friends"><header className="tab-header"><div><small>나의 성장 파트너</small><h1>친구</h1></div></header><section className="friend-card"><Character type={type} className="friend-character"/><span>Lv. {level}</span><h1>{LABELS[type]} {TYPES[type]}</h1><p>{profile.nickname}님의 이야기를 판단하지 않고 들어주는 가장 가까운 친구예요.</p><button className="primary" onClick={()=>setView("chat")}>친구와 대화하기</button></section><BottomNav view={view} setView={setView}/></main>;
 if(view==="settings")return <main className="d app-screen settings"><header className="tab-header"><div><small>내 계정</small><h1>설정</h1></div></header><section className="setting-profile"><button className="profile-button">{profile.nickname.slice(0,1)}</button><div><b>{profile.nickname}</b><span>{LABELS[type]} {TYPES[type]} · Lv. {level}</span></div></section><section className="setting-list"><div><span>언어</span><b>한국어 ›</b></div><label><span>알림 설정<small>퀘스트와 성장 알림</small></span><input type="checkbox" checked={notifications} onChange={e=>setNotifications(e.target.checked)}/><i/></label><div><span>내 정보</span><button onClick={()=>setView("account")}>수정하기 ›</button></div><div><span>앱 정보</span><b>v1.0</b></div></section><BottomNav view={view} setView={setView}/></main>;
 return <main className="d start"><img className="brand-title" src="/branding/dorori-title.png" alt="dorori"/><p>나를 키우는 작은 습관</p><Character type={6} className="start-character"/><div className="start-copy"><span>오늘부터 한 걸음씩</span><h1>나만의 도로리와<br/>함께 성장해요</h1></div><button className="primary" onClick={()=>{setMode("signup");setView("account")}}>무료로 시작하기</button><button className="link" onClick={()=>{setMode("signin");setView("account")}}>이미 계정이 있어요 · 로그인</button></main>
}
