"use client";
import { useState } from "react";
import "./dorori.css";

const URL="https://bltdjctrqlrimpcpdfbl.supabase.co", KEY="sb_publishable_UX5qAOrr5Kk5Hj2li0IQfA_Z2j2lPZF";
const TYPES=["Roy","obby","popo","mumu","nugu","Nabi","pingo","bamba","moa"], LABELS=["방전형","생각과다형","미룸형","눈치형","벽쌓기형","길잃음형","도파민형","꾹참형","나몰라형"];
const REPLIES=["지쳤구나. 오늘은 회복이 먼저야.","마음이 복잡해도 하나씩이면 충분해.","시작은 아주 작아도 괜찮아.","네 마음을 먼저 살펴도 돼.","잠시 거리를 두는 것도 돌봄이야.","방향을 다시 묻는 건 멋진 용기야.","재미를 찾는 마음도 소중해.","참아온 마음을 내려놓아도 괜찮아.","지금 할 수 있는 현실적인 한 가지를 해보자.","오늘의 너도 충분히 잘하고 있어."];
const ENDINGS=["물 한 모금만 마셔볼까?","3분만 같이 해볼까?","지금은 답을 내리지 않아도 돼.","네가 고른 속도를 믿어.","나는 오늘도 네 편이야.","작은 행동 하나면 충분해."];
function response(text:string,type:number,turn:number){const i=/지쳤|피곤|힘들/.test(text)?0:/불안|걱정|무서/.test(text)?1:/미루|해야|시작/.test(text)?2:/외로|혼자/.test(text)?3:/싸웠|화나|갈등/.test(text)?4:/무기력|싫/.test(text)?5:/잘했|성공|기뻐/.test(text)?6:/친구|눈치|사람/.test(text)?7:/밤|잠/.test(text)?8:9;return `${TYPES[type]}가 들었어. ${REPLIES[i]} ${ENDINGS[(text.length+type+turn)%6]}`}

export function DororiClient(){
 const [view,setView]=useState("start"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState("signup"),[status,setStatus]=useState(""),[type,setType]=useState(0),[input,setInput]=useState(""),[turn,setTurn]=useState(0),[messages,setMessages]=useState([{me:false,t:"왔구나. 오늘은 어떤 하루였어? 한 문장이어도 괜찮아."}]);
 const auth=async()=>{setStatus("확인 중이에요…");const r=await fetch(URL+(mode==="signup"?"/auth/v1/signup":"/auth/v1/token?grant_type=password"),{method:"POST",headers:{apikey:KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password,options:{emailRedirectTo:location.origin}})}),d=await r.json();if(!r.ok)return setStatus(d.error_description||"다시 확인해 주세요.");if(!d.access_token)return setStatus("인증 메일을 보냈어요. 메일 링크를 누른 뒤 로그인해 주세요.");localStorage.setItem("dorori_token",d.access_token);setView("home")};
 const send=(text=input)=>{if(!text.trim())return;setMessages(x=>[...x,{me:true,t:text},{me:false,t:response(text,type,turn)}]);setInput("");setTurn(turn+1)};
 if(view==="account")return <main className="d"><button className="back" onClick={()=>setView("start")}>‹</button><div className="sprout">🌱</div><h1>{mode==="signup"?"dorori 회원가입":"dorori 로그인"}</h1><p>나만의 캐릭터와 오늘의 기록을 안전하게 이어가요.</p><input placeholder="이메일" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="비밀번호 6자 이상" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary" onClick={auth}>{mode==="signup"?"회원가입":"로그인"}</button><p>{status}</p><button className="link" onClick={()=>setMode(mode==="signup"?"signin":"signup")}>{mode==="signup"?"이미 계정이 있어요 · 로그인":"처음이에요 · 회원가입"}</button></main>;
 if(view==="chat")return <main className="d chat"><header><button className="back" onClick={()=>setView("home")}>‹</button><b>🌱 {TYPES[type]}<small>오늘 곁에 있는 친구 · 540가지 반응</small></b></header><div className="talk">{messages.map((x,i)=><div key={i} className={x.me?"me":"bot"}>{x.t}</div>)}</div><div className="chips">{["에너지가 바닥났어","마음이 복잡해","작은 일부터 할래"].map(x=><button key={x} onClick={()=>send(x)}>{x}</button>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="오늘의 마음을 들려줘"/><button>↑</button></form></main>;
 if(view==="home")return <main className="d"><header><small>오늘의 돌봄</small><button onClick={()=>setView("account")}>☻</button></header><h1>안녕! ☀️</h1><p>오늘도 잘 하고 있어요.</p><div className="hero"><div>🌱</div><small>Lv. 07 · {LABELS[type]} {TYPES[type]}</small><h2>작은 돌봄을<br/>선물해볼까요?</h2><b>●●●○○ 230 / 500 잎사귀</b></div><h2>오늘의 성장 퀘스트</h2>{["💧 물 한 잔으로 하루 시작하기","👟 10분 산책하기","💗 나에게 따뜻한 말 한마디 하기"].map(x=><button className="mission" key={x}>{x}<i>+</i></button>)}<button className="primary bottom" onClick={()=>setView("chat")}>친구와 대화하기</button></main>;
 return <main className="d start"><div className="brand">dorori</div><p>나를 키우는 작은 습관</p><div className="sprout">🌱<span>오늘도<br/>수고했어!</span></div><h1>{LABELS[type]} {TYPES[type]}와<br/>작은 습관을 시작해요</h1><div className="types">{TYPES.map((n,i)=><button key={n} onClick={()=>setType(i)} className={i===type?"chosen":""}>{n}</button>)}</div><button className="primary" onClick={()=>setView("home")}>시작하기</button><button className="link" onClick={()=>setView("account")}>로그인 · 회원가입</button></main>
}
